import { canonicalSha256 } from "./canonical-json.ts";
import {
  buildPublicMarketRegistry,
  type CatalogAssetInput,
  type PublicMarketRegistry,
} from "./market-registry.ts";

export const prestocksCatalogFixture = Object.freeze([
  {
    name: "Anduril PreStocks",
    symbol: "ANDURIL",
    description: "Economic exposure to Anduril.",
    imageUrl: "https://www.prestocks.com/logos/anduril.png",
    externalUrl: "https://www.prestocks.com/anduril",
    contractAddress: "PresTj4Yc2bAR197Er7wz4UUKSfqt6FryBEdAriBoQB",
    markPrice: 153.05,
    markValuation: 135_407_295_244,
    tokenPrice: 162.87,
    supply: 11_805.82,
  },
  {
    name: "Anthropic PreStocks",
    symbol: "ANTHROPIC",
    description: "Economic exposure to Anthropic.",
    imageUrl: "https://www.prestocks.com/logos/anthropic.png",
    externalUrl: "https://www.prestocks.com/anthropic",
    contractAddress: "Pren1FvFX6J3E4kXhJuCiAD5aDmGEb7qJRncwA8Lkhw",
    markPrice: 1035.78,
    markValuation: 1_696_969_887_905,
    tokenPrice: 1043.19,
    supply: 7_381.81,
  },
  {
    name: "Figure AI PreStocks",
    symbol: "FIGUREAI",
    description: "Economic exposure to Figure AI.",
    imageUrl: "https://www.prestocks.com/logos/figureai.png",
    externalUrl: "https://www.prestocks.com/figureai",
    contractAddress: "PreZad18qfPtbxNpMtMuAuX2zVpvkEU8DnJx56faCWd",
    markPrice: 180.81,
    markValuation: 39_420_383_962,
    tokenPrice: 170.03,
    supply: 3_012.86,
  },
  {
    name: "Kalshi PreStocks",
    symbol: "KALSHI",
    description: "Economic exposure to Kalshi.",
    imageUrl: "https://www.prestocks.com/logos/kalshi.png",
    externalUrl: "https://www.prestocks.com/kalshi",
    contractAddress: "PreLWGkkeqG1s4HEfFZSy9moCrJ7btsHuUtfcCeoRua",
    markPrice: 881.28,
    markValuation: 32_053_741_720,
    tokenPrice: 873.39,
    supply: 904.87,
  },
  {
    name: "Neuralink PreStocks",
    symbol: "NEURALINK",
    description: "Economic exposure to Neuralink.",
    imageUrl: "https://www.prestocks.com/logos/neuralink.png",
    externalUrl: "https://www.prestocks.com/neuralink",
    contractAddress: "PrekqLJvJ3qVdXmBGDiexvwUTF4rLFDa6HWS4HJbw9S",
    markPrice: 336.46,
    markValuation: 64_094_035_255,
    tokenPrice: 440.31,
    supply: 2_595.28,
  },
  {
    name: "OpenAI PreStocks",
    symbol: "OPENAI",
    description: "Economic exposure to OpenAI.",
    imageUrl: "https://www.prestocks.com/logos/openai.png",
    externalUrl: "https://www.prestocks.com/openai",
    contractAddress: "PreweJYECqtQwBtpxHL171nL2K6umo692gTm7Q3rpgF",
    markPrice: 1023.23,
    markValuation: 1_267_711_624_897,
    tokenPrice: 1355.85,
    supply: 2_826.34,
  },
  {
    name: "Polymarket PreStocks",
    symbol: "POLYMARKET",
    description: "Economic exposure to Polymarket.",
    imageUrl: "https://www.prestocks.com/logos/polymarket.png",
    externalUrl: "https://www.prestocks.com/polymarket",
    contractAddress: "Pre8AREmFPtoJFT8mQSXQLh56cwJmM7CFDRuoGBZiUP",
    markPrice: 144.34,
    markValuation: 15_027_844_690,
    tokenPrice: 146.59,
    supply: 4_816.94,
  },
  {
    name: "SpaceX PreStocks",
    symbol: "SPACEX",
    description: "Economic exposure to SpaceX.",
    imageUrl: "https://www.prestocks.com/logos/spacex.png",
    externalUrl: "https://www.prestocks.com/spacex",
    contractAddress: "PreANxuXjsy2pvisWWMNB6YaJNzr7681wJJr2rHsfTh",
    markPrice: 148.18,
    markValuation: 1_942_756_022_410,
    tokenPrice: 117.48,
    supply: 43_712.53,
  },
] as const satisfies readonly CatalogAssetInput[]);

export async function buildMarketRegistryFixture(): Promise<PublicMarketRegistry> {
  return buildPublicMarketRegistry({
    assets: prestocksCatalogFixture,
    catalogSha256: await canonicalSha256(prestocksCatalogFixture),
    mode: "DETERMINISTIC_REPLAY",
    observedAt: "2026-09-24T16:00:00.000Z",
    sourceUrl: "https://prestocks.com/api/prestocks",
  });
}

